apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtodb
  labels:
    app: produtodb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: produtodb
        tier: database
    spec:
      containers:
        - name:  produtodb
          image: diegobbrito17/produtos-db:latest
          ports:
            - containerPort: 3306
              name: produtodb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_password
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: produto-db-pvc